#!/bin/bash dry-wit
# Copyright 2016-today Automated Computing Machinery S.L.
# Distributed under the terms of the GNU General Public License v3

#set -o xtrace

# The tests
declare -ax TESTS;

# The associative arrays
declare -Ax TEST_ERRORS;
declare -Ax TEST_ERROR_MESSAGES;
declare -Ax TEST_FAILURES;
declare -Ax TEST_SUCCESSES;
declare -Ax TEST_FAILURE_MESSAGES;
declare -Ax TEST_ASSERTION_FAILURES;
declare -Ax TEST_ASSERTION_SUCCESSES;
declare -Ax TEST_ASSERTION_LINE_NUMBERS;
declare -Ax TEST_ASSERTION_FAILURE_MESSAGES;
declare -Ax TEST_ASSERTION_FAILURE_CONTEXT;

addError TEST_WITH_FAILED_ASSERTIONS "Test with failed assertions";
addError TEST_WITH_NO_ASSERTIONS "Test with no assertions";
addError NO_TESTS_FOUND "No tests found";
addError TEST_FAILED "Test failed"

## Retrieves all available tests.
## -> 1: The script name.
## <- RESULT: The space-separated list of tests found.
## Example:
##   DRYWITTEST.retrieveTests "dry-wit";
##   echo "Tests found: ${RESULT}";
function DRYWITTEST.retrieveTests() {
  local _script="${1}";
  local _functions="$(typeset -f | awk '!/^main[ (]/ && /^[^ {}]+ *\(\)/ { gsub(/[()]/, "", $1); print $1}')";
  local _oldIFS="${IFS}";

  if isEmpty "${_functions}"; then
    exitWithErrorCode NO_TESTS_FOUND;
  fi

  IFS="${DWIFS}";
  for _f in ${_functions}; do
    IFS="${_oldIFS}";
    if [ "${_f%*_test}" != "${_f}" ] && [ "${_f}" != "_test" ]; then
      TESTS[${#TESTS[@]}]="${_f}";
    fi
  done
  IFS="${_oldIFS}";

  if isEmpty "${TESTS[@]}"; then
    exitWithErrorCode NO_TESTS_FOUND;
  fi

  export RESULT="${TESTS[@]}";
}

## Annotates a new error when executing a test.
## Note: This function is used by dry-wit itself.
## Example:
##   DRYWITTEST.addTestError "my_test";
function DRYWITTEST.addTestError() {
  local _test="${1}";
  local _message="${2}";
  local -i _count;
  local -i _index;

  checkNotEmpty "test" "${_test}" 1;
  checkNotEmpty "message" "${_message}" 2;

  _count=${TEST_ERRORS[${_test}]};
  if isEmpty "${_count}"; then
      _count=0;
  fi
  _index=${_count};
  _count=$((_count+1));

  TEST_ERRORS["${_test}"]=${_count};
  TEST_ERROR_MESSAGES["${_test}:${_index}"]="${_message}";
}

## PRIVATE
## Removes a detected error for a given test, since it expected in an assertErrorThrown.
## Example:
##   DRYWITTEST.removeTestError "my_test";
function DRYWITTEST.removeTestError() {
  local _test="${1}";
  local -i _count;
  local -i _index;

  checkNotEmpty "test" "${_test}" 1;

  _count=${TEST_ERRORS[${_test}]};
  if ! isEmpty "${_count}"; then
      _index=${_count};
      _count=$((_count-1));
      TEST_ERRORS["${_test}"]=${_count};
      TEST_ERROR_MESSAGES["${_test}:${_index}"]="";
  fi
}

## Annotates a new failed test.
## -> 1: The test name.
## -> 2: The message.
## Example:
##   DRYWITTEST.addTestFailure "my_test" "Failed assertions";
function DRYWITTEST.addTestFailure() {
  local _test="${1}";
  local _message="${2}";
  local -i _count;
  local -i _index;

  checkNotEmpty "test" "${_test}" 1;
  checkNotEmpty "message" "${_message}" 2;

  _count=${TEST_FAILURES["${_test}"]};
  if isEmpty "${_count}"; then
      _count=0;
  fi
  _index=${_count};
  _count=$((_count+1));

  TEST_FAILURES["${_test}"]=${_count};
  TEST_FAILURE_MESSAGES["${_test}:${_index}"]="${_message}";
}

## Annotates a new passed test.
## -> 1: The test name.
## Example:
##   DRYWITTEST.addTestSuccess "my_test";
function DRYWITTEST.addTestSuccess() {
  local _test="${1}";
  local _count;

  _count=${TEST_SUCCESSES["${_test}"]};
  if isEmpty "${_count}"; then
    _count=0;
  fi
  _count=$((_count+1));

  TEST_SUCCESSES["${_test}"]=${_count};
}

## Annotates a new failed test assertion.
## -> 1: The test name.
## -> 2: The error message.
## -> 3: Additional context information (optional).
## Example:
##   DRYWITTEST.addTestAssertionFailure "my_test" "Should not fail";
function DRYWITTEST.addTestAssertionFailure() {
  local _test="${1}";
  local _message="${2}";

  checkNotEmpty "test" "${_test}" 1;
  checkNotEmpty "message" "${_message}" 2;

  local _extra="${3}";
  local _lineNumber="${BASH_LINENO[1]}";
  local -i _count;
  local -i _index;

  _count=${TEST_ASSERTION_FAILURES["${_test}"]};
  if isEmpty "${_count}"; then
      _count=0;
  fi
  _index=${_count};
  _count=$((_count+1));

  TEST_ASSERTION_FAILURES["${_test}"]=${_count};
  TEST_ASSERTION_LINE_NUMBERS["${_test}:${_index}"]=${_lineNumber};
  TEST_ASSERTION_FAILURE_MESSAGES["${_test}:${_index}"]="${_message}";
  if isNotEmpty "${_extra}"; then
      TEST_ASSERTION_FAILURE_CONTEXT["${_test}:${_index}"]="${_extra}";
  fi
}

## Annotates a new passed test assertion.
## -> 1: The test name.
## Example:
##   DRYWITTEST.addTestAssertionSuccess "my_test";
function DRYWITTEST.addTestAssertionSuccess() {
  local _test="${1}";
  local _count;

  _count=${TEST_ASSERTION_SUCCESSES["${_test}"]};
  if isEmpty "${_count}"; then
    _count=0;
  fi
  _count=$((_count+1));
  TEST_ASSERTION_SUCCESSES["${_test}"]=${_count};
}

## Retrieves the number of passing assertions for given test.
## -> 1: The test name.
## Example:
##   retrievePassingTestAssertions "my_test";
##   echo "my_test: ${RESULT} assertions passed"
function retrievePassingTestAssertions() {
  local _test="${1}";
  local _result;

  _result=${TEST_ASSERTION_SUCCESSES["${_test}"]};
  if isEmpty "${_result}"; then
    _result=0;
  fi

  export RESULT="${_result}";
}

## Retrieves the number of failed assertions for given test.
## -> 1: The test name.
## Example:
##   retrieveFailedTestAssertions "my_test";
function retrieveFailedTestAssertions() {
  local _test="${1}";
  local _result;

  _result=${TEST_ASSERTION_FAILURES["${_test}"]};
  if isEmpty "${_result}"; then
    _result=0;
  fi

  export RESULT="${_result}";
}

## Checks whether all assertions passed for given test.
## -> 1: The test.
## <- 0/${TRUE} if all assertions passed; 1/${FALSE} otherwise.
## Example:
##   if DRYWITTEST.allAssertionsPassed "my_test"; then
##     echo "Hurray!";
##   fi
function DRYWITTEST.allAssertionsPassed() {
  local _test="${1}";
  local -i _failed;
  local -i _rescode;

  retrieveFailedTestAssertions "${_test}";
  _failed=${RESULT};

  if [ ${_failed} -eq 0 ]; then
    _rescode=${TRUE};
  else
    _rescode=${FALSE};
  fi

  return ${_rescode};
}

## Checks whether all assertions passed for given test.
## -> 1: The test.
## <- 0/${TRUE} if all assertions passed; 1/${FALSE} otherwise.
## Example:
##   if DRYWITTEST.noAssertionsPassed "my_test"; then
##     echo "Too bad!";
##   fi
function DRYWITTEST.noAssertionsPassed() {
  local _test="${1}";
  local -i _passing;
  local -i _rescode;

  retrievePassingTestAssertions "${_test}";
  _passing=${RESULT};

  if [ ${_passing} -eq 0 ]; then
    _rescode=${TRUE};
  else
    _rescode=${FALSE};
  fi

  return ${_rescode};
}

## Checks whether given test defined no assertions.
## -> 1: The test.
## <- 0/${TRUE} if the test includes no assertions; 1/${FALSE} otherwise.
## Example:
##   if DRYWITTEST.noAssertionsDefined "my_test"; then
##     echo "Error: no assertions defined in my_test";
##   fi
function DRYWITTEST.noAssertionsDefined() {
  local _test="${1}";
  local -i _failed;
  local _i _passing;
  local -i _rescode;

  if DRYWITTEST.allAssertionsPassed "${_test}"; then
    if DRYWITTEST.noAssertionsPassed "${_test}"; then
      _rescode=${TRUE};
    else
      _rescode=${FALSE};
    fi
  else
    _rescode=${FALSE};
  fi

  return ${_rescode};
}

## Runs given test.
## -> 1: The test to run.
## <- 0/${TRUE} if the test passes; 1/${FALSE} otherwise.
## Example:
##   run_test "my_test"
##   if isTrue $?; then
##     echo "my_test passes";
##   fi
function runTest() {
  local _test="${1}";
  local _assertions;
  local _rescode;

  if isFunctionPresent "test_setup"; then
    test_setup;
  fi

#  ${_test} > /dev/null 2>&1;
  ${_test}
  if isTrue $?; then
    if DRYWITTEST.noAssertionsDefined "${_test}"; then
      DRYWITTEST.addTestFailure "${_test}" TEST_WITH_NO_ASSERTIONS;
      _rescode=${FALSE};
    elif DRYWITTEST.allAssertionsPassed "${_test}"; then
      DRYWITTEST.addTestSuccess "${_test}";
      _rescode=${TRUE};
    else
      DRYWITTEST.addTestFailure "${_test}" TEST_WITH_FAILED_ASSERTIONS;
      _rescode=${FALSE};
    fi
  else
    DRYWITTEST.addTestError "${_test}" TEST_FAILED;
  fi

  if isFunctionPresent "test_tearDown"; then
    test_tearDown;
  fi

  return ${_rescode};
}

## Annotates a test success.
## -> 1: The function name.
## Example:
##   DRYWITTEST.annotateTestSuccess "my_test";
function DRYWITTEST.annotateTestSuccess() {
  DRYWITTEST.addTestSuccess "${_test}";
}

## Retrieves tests with issues of some kind.
## <- RESULT: The space-separated names of the tests with some issues.
## Example:
##   DRYWITTEST.retrieveTestsWithIssues;
##   echo "Tests with issues: ${RESULT}";
function DRYWITTEST.retrieveTestsWithIssues() {
  local _result="";
  local _test;
  local _errors;
  local _failures;
  local _successes;
  local _assertionFailures;
  local _assertionSuccesses;
  local _oldIFS="${IFS}";

  IFS=$' \t\n';
  for _test in ${TESTS[@]}; do
    IFS="${_oldIFS}";
    _errors="${TEST_ERRORS[${_test}]}";
    _failures="${TEST_FAILURES[${_test}]}";
    _assertionFailures="${TEST_ASSERTION_FAILURES[${_test}]}";

    if ! isEmpty "${_errors}" || ! isEmpty "${_failures}" || ! isEmpty "${_assertionFailures}"; then
      _result="${_result} ${_test}";
    fi
  done
  IFS="${_oldIFS}";

  export RESULT="${_result}";
}

### REPORTING

## Logs a summary of the tests.
## Example:
##   DRYWITTEST.logSummary;
function DRYWITTEST.logSummary() {
  local _oldIFS="${IFS}";
  local _test;

  IFS="${DWIFS}";
  for _test in ${TESTS[@]}; do
    IFS="${_oldIFS}";
    DRYWITTEST.logTestSummary "${_test}";
  done
  IFS="${_oldIFS}";
}

## Logs the detailed information about why a given test has thrown errors.
## -> 1: the test name.
## Example:
##   DRYWITTEST.logErrorReasons "my_test";
function DRYWITTEST.logErrorReasons() {
  local _test="${1}";
  local _count=${TEST_ERRORS[${_test}]};
  local -i _i=0;
  local _error;
  local _message;
  local _lineNumber;
  local _oldIFS="${IFS}";

  if [ ${_count} -gt 0 ]; then
    IFS=$' \t\n';
    for _i in $(seq 0 $((_count-1))); do
      IFS="${_oldIFS}";
      _error="${TEST_ERROR_MESSAGES[${_test}:${_i}]}";
      evalConstant "${_error}" "${_error}";
      _message="${RESULT}";
      logInfo -n "${_message}";
      logInfoResult FAILURE "${_test}";
    done
    IFS="${_oldIFS}";
  fi
}

## Logs the detailed information about why a given test has failed.
## -> 1: the test name.
## Example:
##   DRYWITTEST.logFailureReasons "my_test";
function DRYWITTEST.logFailureReasons() {
  local _test="${1}";
  local _count=${TEST_FAILURES[${_test}]};
  local -i _i=0;
  local _error;
  local _message;
  local _lineNumber;
  local _oldIFS="${IFS}";

  if [ ${_count} -gt 0 ]; then
    IFS="${DWIFS}";
    for _i in $(seq 0 $((_count-1))); do
      IFS="${_oldIFS}";
      _error="${TEST_FAILURE_MESSAGES[${_test}:${_i}]}";
      evalConstant "${_error}" "${_error}";
      _message="${RESULT}";
      logInfo -n "${_message}";
      logInfoResult FAILURE "${_test}";
    done
    IFS="${_oldIFS}";
  fi
}

## Logs the failed assertions for given test.
## -> 1: the test name.
## Example:
##   DRYWITTEST.logFailedAssertions "my_test";
function DRYWITTEST.logFailedAssertions() {
  local _test="${1}";
  local _count=${TEST_ASSERTION_FAILURES[${_test}]};
  local -i _i=0;
  local _error;
  local _message;
  local _lineNumber;
  local _context;
  local _oldIFS="${IFS}";

  if [ ${_count} -gt 0 ]; then
    IFS="${DWIFS}";
    for _i in $(seq 0 $((_count-1))); do
      IFS="${_oldIFS}";
      _lineNumber="${TEST_ASSERTION_LINE_NUMBERS[${_test}:${_i}]}";
      _error="${TEST_ASSERTION_FAILURE_MESSAGES[${_test}:${_i}]}";
      evalConstant "${_error}" "${_error}";
      _message="${RESULT}";
      _context="${TEST_ASSERTION_FAILURE_CONTEXT[${_test}:${_i}]}";
      if isEmpty "${_context}"; then
        logInfo -n "${_message}";
      else
        logInfo -n "${_message}: ${_context}";
      fi
      logInfoResult FAILURE "${_test}:${_lineNumber}";
    done
    IFS="${_oldIFS}";
  fi
}

## Logs a summary of given test.
## -> 1: The test name.
## Example:
##   DRYWITTEST.logTestSummary "my_test";
function DRYWITTEST.logTestSummary() {
  local _test="${1}";
  local _errors;
  local _failures;
  local _successes;
  local _assertionFailures;
  local _assertionSuccesses;

  checkNotEmpty "test" "${_test}" 1;

  _errors="${TEST_ERRORS[${_test}]}";
  if isEmpty "${_errors}" || [ ${_errors} -eq 0 ]; then
    _failures="${TEST_FAILURES[${_test}]}";
    _assertionFailures="${TEST_ASSERTION_FAILURES[${_test}]}";
    if isEmpty "${_assertionFailures}" || [ ${_assertionFailures} -eq 0 ]; then
        logInfo -n "Test ${_test}: assertions passed";
        _assertionSuccesses="${TEST_ASSERTION_SUCCESSES[${_test}]}";
        if isEmpty "${_assertionSuccesses}"; then
            logInfoResult FAILURE "0";
        else
          logInfoResult SUCCESS "${_assertionSuccesses}";
        fi
    else
      logInfo -n "Test ${_test}: assertions failed";
      logInfoResult FAILURE "${_assertionFailures}";
      DRYWITTEST.logFailedAssertions "${_test}";
      logInfo -n "Test ${_test}: failures";
      logInfoResult FAILURE "${_failures}";
      DRYWITTEST.logFailureReasons "${_test}";
    fi
  else
    logInfo -n "Test ${_test}: errors";
    logInfoResult FAILURE "${_errors}";
    logErrorReasons "${_test}";
  fi
}

function retrieveScriptName() {
  local _testFile="${0}";
}

function DRYWITTEST.dwtest() {
  local _tests;
  local _failedTests;
  local _t;
  local _oldIFS="${IFS}";
  local _scriptName;
  retrieveScriptName;

  logInfo -n "Retrieving tests in ${SCRIPT_NAME}";
  DRYWITTEST.retrieveTests ${SCRIPT_NAME};
  _tests="${RESULT}";
  if isEmpty "${_tests}"; then
    logInfoResult FAILURE "0";
    exitWithErrorCode NO_TESTS_FOUND;
  else
    logInfoResult SUCCESS "$(echo "${_tests}" | wc -w)";
  fi

  IFS=${DWIFS};
  for _t in ${_tests}; do
    IFS="${_oldIFS}";
    logInfo -n "Running ${_t}";
    if runTest "${_t}"; then
      logInfoResult SUCCESS "pass";
    else
      logInfoResult FAILURE "failed";
    fi
  done
  IFS="${_oldIFS}";

  DRYWITTEST.retrieveTestsWithIssues;
  _failedTests="${RESULT}";
  if isNotEmpty "${_failedTests}"; then
    IFS="${DWIFS}";
    for _t in ${_failedTests}; do
      IFS="${_oldIFS}";
      DRYWITTEST.logTestSummary "${_t}";
    done
    IFS="${_oldIFS}";
  fi
}

## Calling dry-wit from a well-known place
function __dwCallback() {
  _defineDryWitErrorMessages;
  DWTEST.defineErrors;
  if isFunctionPresent defineErrors "${SCRIPT_NAME}"; then
      defineErrors;
  else
    export -a ERROR_MESSAGES=();
  fi
}

### ASSERTIONS ###

## Asserts given condition holds true.
## -> 1: the condition to check.
## -> 2: the error message.
## Example:
##   Assert.isTrue [ 1 == 1 ] "check [ 1 == 1 ] failed";
function Assert.isTrue() {
  local -i _condition=${1};
  local _error="${2}";

  checkNotEmpty "condition" "${_condition}" 1;
  checkNotEmpty "error" "${_error}" 2;

  if isTrue ${_condition}; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_error}";
  fi
}

## Asserts given condition holds true.
## -> 1: the condition to check.
## -> 2: the error message.
## Example:
##   Assert.isFalse [ 1 != 1 ], "check [ 1 != 1 ] failed";
function Assert.isFalse() {
  local _condition=${1};
  local _error="${2}";

  checkNotEmpty "condition" "${_condition}" 1;
  checkNotEmpty "error" "${_error}" 2;

  if isFalse ${_condition}; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_error}";
  fi
}

## Asserts no error has been thrown so far in current test.
## -> 1: The error message.
## Example:
##   [call functionX]
##   Assert.noErrorThrown "functionX has thrown an error";
function Assert.noErrorThrown() {
  local _message="${1}";

  checkNotEmpty "message" "${_message}" 1;

  local _errors=${TEST_ERRORS["${FUNCNAME[1]}"]};
  if isEmpty "${_errors}"; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}";
  fi
}

## Asserts an error has been thrown so far in current test.
## -> 1: The error message.
## Example:
##   [call functionX]
##   Assert.errorThrown "functionX should have thrown an error";
function Assert.errorThrown() {
  local _message="${1}";

  checkNotEmpty "message" "${_message}" 1;

  local _errors=${TEST_ERRORS["${FUNCNAME[1]}"]};
  if isEmpty "${_errors}"; then
      DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${1}";
  else
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
    DRYWITTEST.removeTestError "${FUNCNAME[1]}";
  fi
}

## Asserts both values are equal.
## -> 1: The expected value.
## -> 2: The actual value.
## -> 3: The error message.
## Example:
##   Assert.areEqual 1 1 "1 does not equal 1";
function Assert.areEqual() {
  local _expected="${1}";
  local _actual="${2}";
  local _message="${3}";

#  checkNotEmpty "expected" "${_expected}" 1;
#  checkNotEmpty "actual" "${_actual}" 2;
  checkNotEmpty "message" "${_message}" 3;

  if areEqual "${_expected}" "${_actual}"; then
      DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}" "(${_expected} != ${_actual})";
  fi
}

## Asserts both values are different.
## -> 1: The expected value.
## -> 2: The actual value.
## -> 3: The error message.
## Example:
##   Assert.areNotEqual 1 2 "1 is equal to 2";
function Assert.areNotEqual() {
  local _expected="${1}";
  local _actual="${2}";
  local _message="${3}";

  checkNotEmpty "expected" "${_expected}" 1;
  checkNotEmpty "actual" "${_actual}" 2;
  checkNotEmpty "message" "${_message}" 3;

  if areNotEqual "${_expected}" "${_actual}"; then
      DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}" "(${_expected} == ${_actual})";
  fi
}

## Asserts given value is empty.
## -> 1: The value.
## -> 2: The error message.
## Example:
##   Assert.isEmpty "${testValue}" "testValue is not empty";
function Assert.isEmpty() {
  local _value="${1}";
  local _message="${2}";

  checkNotEmpty "message" "${_message}" 2;

  if isEmpty "${_value}"; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}" "(${_value} is not empty)";
  fi
}

## Asserts given value is not empty.
## -> 1: The value.
## -> 2: The error message.
## Example:
##   Assert.isNotEmpty "${testValue}" "testValue is empty";
function Assert.isNotEmpty() {
  local _value="${1}";
  local _message="${2}";

  if isNotEmpty "${_value}"; then
    checkNotEmpty "message" "${_message}" 2;

    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}" "(${_value} is empty)";
  fi
}

## Asserts given value is an existing function.
## -> 1: The function name.
## -> 2: The error message.
## Example:
##   Assert.functionExists "my_function" "my_function does not exist";
function Assert.functionExists() {
  local _functionName="${1}";
  local _message="${2}";

  if isNotEmpty "${_functionName}"; then
    checkNotEmpty "message" "${_message}" 2;

    if isFunctionPresent "${_functionName}"; then
      DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
    else
      DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}" "(${_functionName} is not defined)";
    fi
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_message}" "(${_functionName} is not defined)";
  fi
}

## Fails the test directly.
## -> 1: The error message. Mandatory.
## Example:
##   fail "my_test";
function Assert.fail() {
  local _message="${1}";

  checkNotEmpty "errorMessage" "${_message}" 1;

  DRYWITTEST.addTestFailure "${FUNCNAME[1]}" "${_message}";
}

## Checks a substring is contained in given text.
## -> 1: The text.
## -> 2: The substring.
## -> 3: The error message.
## Example:
##   Assert.contains "sample text" "sample" "'sample text' does not contain 'sample'";
function Assert.contains() {
  local _text="${1}";
  local _substring="${2}";
  local _errorMessage="${3}";

  checkNotEmpty "text" "${_text}" 1;
  checkNotEmpty "substring" "${_substring}" 2;
  checkNotEmpty "errorMessage" "${_errorMessage}" 3;

  if contains "${_text}" "${_substring}"; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_errorMessage}" "('${_text}' does not contain '${_substring}')";
  fi
}

## Checks a file contains a text.
## -> 1: The file.
## -> 2: The text to test.
## -> 3: The error message.
## Example:
##   Assert.fileContains "/tmp/debug.log" "TESTING" "/tmp/debug.log doesn't contain TESTING";
function Assert.fileContains() {
  local _file="${1}";
  local _text="${2}";
  local _errorMessage="${3}";

  checkNotEmpty "file" "${_file}" 1;
  checkNotEmpty "text" "${_text}" 2;
  checkNotEmpty "errorMessage" "${_errorMessage}" 3;

  if grep -q "${_text}" "${_file}" 2> /dev/null; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_errorMessage}" "('${_text}' does not contain '${_actual}')";
  fi
}

## Checks an array contains a text.
## -> 1: The array.
## -> 2: The text to test.
## -> 3: The error message.
## Example:
##   Assert.arrayContains "${array[@]}" "TESTING" "array doesn't contain TESTING";
function Assert.arrayContains() {
  local _array="${1}";
  local _text="${2}";
  local _errorMessage="${3}";

  checkNotEmpty "array" "${_array}" 1;
  checkNotEmpty "text" "${_text}" 2;
  checkNotEmpty "errorMessage" "${_errorMessage}" 3;

  if arrayContains "${_array}" "${_text}"; then
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  else
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_errorMessage}" "('${_text}' does not contain '${_actual}')";
  fi
}

## Checks an array doesn't contain a text.
## -> 1: The array.
## -> 2: The text to test.
## -> 3: The error message.
## Example:
##   Assert.arrayDoesNotContain "${array[@]}" "TESTING" "array contains TESTING";
function Assert.arrayDoesNotContain() {
  local _array="${1}";
  local _text="${2}";
  local _errorMessage="${3}";

  checkNotEmpty "array" "${_array}" 1;
  checkNotEmpty "text" "${_text}" 2;
  checkNotEmpty "errorMessage" "${_errorMessage}" 3;

  if arrayContains "${_array}" "${_text}"; then
    DRYWITTEST.addTestAssertionFailure "${FUNCNAME[1]}" "${_errorMessage}" "('${_text}' contains '${_actual}')";
  else
    DRYWITTEST.addTestAssertionSuccess "${FUNCNAME[1]}";
  fi
}

## Sources the Subject-under-test, if found, using a convention.
## If the tests are in foo-tests.sh, it'll try to source ./foo.sh first.
## If it doesn't exist, then it'll try to source ../src/foo.sh.
function DRYWITTEST.sourceSUT() {
  local -i _rescode;
  local _sutFilename;
  local _sutFilePath;

  if removeSuffix "${SCRIPT_NAME}" "-tests.sh"; then
    _sutFilename="${RESULT}.sh";
    _rescode=${TRUE};
  elif removeSuffix "${SCRIPT_NAME}" "-test.sh"; then
    _sutFilename="${RESULT}.sh";
    _rescode=${TRUE};
  else
    echo "Could not find out the name of the sut for ${SCRIPT_NAME}";
    _rescode=${FALSE};
  fi

  if isTrue ${_rescode}; then
    if fileExists "$(dirname $0)/${_sutFilename}"; then
      _sutFilePath="$(dirname $0)/${_sutFilename}";
    elif fileExists "$(dirname $0)/../src/${_sutFilename}"; then
      _sutFilePath="$(dirname $0)/../src/${_sutFilename}";
    else
      echo "Could not find out the folder of the sut for $(dirname $0)/${_sutFilename}";
      _rescode=${FALSE};
    fi
  fi

  if isTrue ${_rescode}; then
    source "${_sutFilePath}";
  fi

  return ${_rescode};
}

function main() {
  DRYWITTEST.sourceSUT;
  DRYWITTEST.dwtest;
}
#
